version: "3.8"
services:
  postgres_db:
    image: postgres:16
    ports:
      - "5432:5432"
    container_name: postgres_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shipment" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_DB: shipment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "max_wal_senders=20",
      "-c", "max_replication_slots=20"
    ]
    secrets:
      - db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../scripts/sql:/docker-entrypoint-initdb.d:ro

  debezium:
    image: debezium/connect:2.6
    container_name: debezium
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
      GROUP_ID: "connect-cluster-1"
      CONFIG_STORAGE_TOPIC: "connect-configs"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KEY_CONVERTER_SCHEMAS_ENABLE: "true"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      postgres_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS localhost:8083/connectors || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

volumes:
  pgdata:

secrets:
  db_password:
    file: ../../secrets/postgres_password.txt