apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: parcelhub
spec:
  serviceName: kafka-headless
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.7
          ports:
            - name: internal
              containerPort: 9092
            - name: controller
              containerPort: 9093
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"

            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "y4s8C7w5QOiK3Nq2Yzv6g"

            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controlle"

            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka-headless.parcelhub.svc.cluster.local:9093,2@kafka-1.kafka-headless.parcelhub.svc.cluster.local:9093,3@kafka-2.kafka-headless.parcelhub.svc.cluster.local:9093"

            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9092,CONTROLLER://:9093"

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT"

            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"

            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "false"

            - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"

            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"

            - name: KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"

            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"


          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka

          startupProbe:
            tcpSocket:
              port: internal
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12

          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 5

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi


