apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: parcelhub
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: kafka
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093

  