apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio
  namespace: parcelhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
        - name: apicurio
          image: apicurio/apicurio-registry-mem:2.5.10.Final
          ports:
            - name: http
              containerPort: 8080

          readinessProbe:
            httpGet:
              path: /apis/registry/v2
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /apis/registry/v2
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
