apiVersion: batch/v1
kind: Job
metadata:
  name: kakfa-init
  namespace: parcelhub
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
        - name: kafka-init
          image: bitnamilegacy/kafka:3.7.0
          env:
            - name: BOOTSTRAP
              value: kafka-bootstrap
          command:
            - bash
            - -lc
            - /scripts/create-topics.sh
          volumeMounts:
            - mountPath: /scripts
              name: scripts
      restartPolicy: OnFailure

      volumes:
        - name: scripts
          configMap:
            name: kafka-init-scripts
            defaultMode: 0755

  