apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: parcelhub
spec:
  serviceName: postgres-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent

          ports:
            - name: postgres
              containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: shipment
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD_FILE
              value: /run/secrets/db_password

          args:
            - postgres
            - -c
            - wal_level=logical
            - -c
            - max_wal_senders=20
            - -c
            - max_replication_slots=20

          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - shipment
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - shipment
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - shipment
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data

            - name: postgres-secret
              mountPath: /run/secrets
              readOnly: true

            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

      volumes:
        - name: postgres-secret
          secret:
            secretName: postgres-secret
            defaultMode: 0400

        - name: init-scripts
          configMap:
            name: postgres-init-scripts

  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        # storageClassName: standard